name: GamemodePerWorld
main: WorldGM\WorldGM
version: 0.5
api: [3.0.0]
load: POSTWORLD
author: Suerion
description: Set different gamemodes for certain worlds
commands:
 wgm:
  description: Set different gamemodes, for different worlds.
  usage: "/wgm set <gamemode> (world)\n/wgm <include/exclude> <player>\n/wgm version\n/wgm check\n/wgm gm\n/wgm update"
  permission: worldgm.use
 s:
  description: Go into Survival mode
  usage: "/s"
  permission: worldgm.survival
 c:
  description: Go into Creative mode
  usage: "/c"
  permission: worldgm.creative
 a:
  description: Go into Adventure mode
  usage: "/a"
  permission: worldgm.adventure
 sp:
  description: Go into Spectator mode
  usage: "/sp"
  permission: worldgm.spectator
permissions:
 worldgm.use:
  description: "Allows users to set world gamemodes"
  default: op
 worldgm.survival:
  description: "Allows players to set themselves to survival"
  default: op
 worldgm.creative:
  description: "Allows players to set themselves to creative"
  default: op
 worldgm.adventure:
  description: "Allows players to set themselves to adventure"
  default: op
 worldgm.spectator:
  description: "Allows players to set themselves to spectator"
  default: op
