#Forked from WorldGM by Exxarion
#https://github.com/Exxarion/WorldGM
#  _____                     
# | ____|_  ____  __ ___ _ __(_) ___  _ __   
# |  _| \ \/ /\ \/ / _` | '__| |/ _ \| '_ \  
# | |___ >  <  >  < (_| | |  | | (_) | | | | 
# |_____/_/\_\/_/\_\__,_|_|  |_|\___/|_| |_| 
#
#Updated and edited by
# _____                 _             
#/  ___|               (_)            
#\ `--. _   _  ___ _ __ _  ___  _ __  
# `--. \ | | |/ _ \ '__| |/ _ \| '_ \ 
#/\__/ / |_| |  __/ |  | | (_) | | | |
#\____/ \__,_|\___|_|  |_|\___/|_| |_|
                                                                                                                                          
# WorldGM EMPTY config file
#
#
excluded: [] #These are players who are not affected by World Gamemodes.
worlds: [] #Worlds that are set by the plugin will appear here.
